# Generated by Django 4.1.13 on 2024-08-22 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTable',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('084f9e2f-fda2-4c9e-a8c3-68d36ba6a190'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('email', models.CharField(max_length=2056, null=True)),
                ('password', models.CharField(max_length=256, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
